/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolion;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author mohamed
 */
public class TeacherFram extends javax.swing.JFrame {

    /**
     * Creates new form TeacherFram
     */
    query q;
    String Tid;
    ResultSet res;
    public TeacherFram() {
        initComponents();
        q = new query();
        Tid = "810000130";
        res = q.ShowTeacherInfo(Tid);
        RefreshTextFields(res); //<- el function de feha exception ya hamada - lazam t7lha el 2wel 3l4an t run
        ViewTeacherSchedule();
        fillTeacherClassesComboBox();
        fillTeacherSubjectsComboBox();
    }
     
    private void RefreshTextFields(ResultSet rslt)
    {
        ArrayList<String> row = new ArrayList<String>(9);
        try {
            while(rslt.next())
            {
                for (int i = 1; i <= 9; i++) {
                    row.add(rslt.getString(i));
                }
            }
            TeacherName_txt.setText(row.get(0)+" "+row.get(1)+" "+row.get(2));
            TeacherID_txt.setText(row.get(3));
            TeacherAddress_txt.setText(row.get(4));
            TeacherPhone_txt.setText(row.get(5));
            TeacherEmail_txt.setText(row.get(6));
            TeacherPosition_txt.setText(row.get(7));
            TeacherBus_Number_txt.setText(row.get(8));
        } catch (SQLException ex) {
            Logger.getLogger(TeacherFram.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void ViewTeacherSchedule()
    {
            try {
            DefaultTableModel mytable = (DefaultTableModel)TeacherScheduleTable.getModel();
            mytable.setValueAt("  Saturday", 0,0);
            mytable.setValueAt("   Sunday", 1,0 );
            mytable.setValueAt("   Monday", 2,0 );
            mytable.setValueAt("  Tuesday", 3,0 );
            mytable.setValueAt(" Wednesday", 4,0 );
            mytable.setValueAt("   Thursday",5,0 );
            mytable.setValueAt("    Friday", 6,0 );
            String classid,subcode,teachid,name = "";
            int day = 0,period = 0;
            res = q.getClassCodeTeachid(Tid);
            ResultSet res1,res2;
            while(res.next()) {
            classid = res.getString(1);
            subcode = res.getString(2);
            teachid = res.getString(3);
            res1 = q.getSubjectName(subcode);
            while(res1.next()){
            name = res1.getString(1);
            res2 = q.getDayPeriod(teachid);
            while(res2.next()) {
            day = Integer.parseInt(res2.getString(1));
            period = Integer.parseInt(res2.getString(2));
            }
            if(!name.isEmpty() && day != 0 && period != 0) {
            mytable.setValueAt("  " + classid + "   " + name, day-1, period);
            name = "";
            day = 0;
            period = 0;
            }
            }
            }
            } catch (SQLException ex) {
            Logger.getLogger(TeacherFram.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    
    private void fillTeacherClassesComboBox()
    {
        try {
            res = q.getTeacherClasses(Tid);
            while(res.next())
            {
                TeacherClassesComboBox.addItem(res.getString("cid"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(TeacherFram.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void fillTeacherSubjectsComboBox()
    {
        try {
            res = q.getSubjectOfTeacherClass(Tid, (String) TeacherClassesComboBox.getSelectedItem());
            while(res.next())
            {
                SubjectCompobox.addItem(res.getString("code"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(TeacherFram.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        TeacherName_txt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TeacherID_txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TeacherPosition_txt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TeacherBus_Number_txt = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TeacherPhone_txt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TeacherAddress_txt = new javax.swing.JTextField();
        TeacherEmail_txt = new javax.swing.JTextField();
        RefreshButton = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        New_TeacherEmail_txt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        New_TeacherAddress_txt = new javax.swing.JTextField();
        New_TeacherPhone_txt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        DoneButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TeacherScheduleTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        TeacherClassesComboBox = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ClassTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        ScienceField_txt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ClassID_txt = new javax.swing.JTextField();
        Capacity_txt = new javax.swing.JTextField();
        NumStudents_txt = new javax.swing.JTextField();
        LevelClass_txt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        GradesButton = new javax.swing.JButton();
        StudentsButton = new javax.swing.JButton();
        EditGradesButton = new javax.swing.JButton();
        SubjectCompobox = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        RefreshClassButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Personal Information"));

        jLabel3.setText("Position:");

        TeacherName_txt.setEnabled(false);
        TeacherName_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeacherName_txtActionPerformed(evt);
            }
        });

        jLabel1.setText("  Name:");

        TeacherID_txt.setEnabled(false);
        TeacherID_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeacherID_txtActionPerformed(evt);
            }
        });

        jLabel2.setText("          ID :");

        TeacherPosition_txt.setEnabled(false);
        TeacherPosition_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeacherPosition_txtActionPerformed(evt);
            }
        });

        jLabel7.setText("Bus Number:");

        TeacherBus_Number_txt.setEnabled(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel7))
                .addGap(32, 32, 32)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TeacherName_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(TeacherID_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TeacherPosition_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TeacherBus_Number_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TeacherName_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TeacherID_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(TeacherPosition_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TeacherBus_Number_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Contact Information"));

        jLabel4.setText("Address:");

        jLabel6.setText("Phone:");

        TeacherPhone_txt.setEnabled(false);
        TeacherPhone_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeacherPhone_txtActionPerformed(evt);
            }
        });

        jLabel5.setText("E-mail:");

        TeacherAddress_txt.setEnabled(false);

        TeacherEmail_txt.setEnabled(false);

        RefreshButton.setText("Refresh");
        RefreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TeacherEmail_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addComponent(TeacherPhone_txt)
                    .addComponent(TeacherAddress_txt))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RefreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TeacherPhone_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TeacherEmail_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TeacherAddress_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(RefreshButton)
                .addGap(8, 8, 8))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Edit Contact Info")));

        New_TeacherEmail_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                New_TeacherEmail_txtActionPerformed(evt);
            }
        });

        jLabel10.setText("New Address:");

        New_TeacherAddress_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                New_TeacherAddress_txtActionPerformed(evt);
            }
        });

        New_TeacherPhone_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                New_TeacherPhone_txtActionPerformed(evt);
            }
        });

        jLabel9.setText("New E-mail:");

        jLabel8.setText("New Phone:");

        DoneButton.setText("Done");
        DoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneButtonActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(New_TeacherPhone_txt))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(New_TeacherEmail_txt))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(New_TeacherAddress_txt))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap(163, Short.MAX_VALUE)
                        .addComponent(DoneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(New_TeacherPhone_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(27, 27, 27)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(New_TeacherEmail_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(New_TeacherAddress_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DoneButton)
                    .addComponent(CancelButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        jTabbedPane1.addTab("My info", jPanel1);

        TeacherScheduleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Day   /  Period", "1st", "2nd  ", "3rd ", "4th", "5th", "6th", "7th"
            }
        ));
        TeacherScheduleTable.setEnabled(false);
        TeacherScheduleTable.setRowHeight(64);
        jScrollPane1.setViewportView(TeacherScheduleTable);

        jTabbedPane1.addTab("My Schedule", jScrollPane1);

        jLabel11.setText("Select Class :");

        ClassTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(ClassTable);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Class Information"));

        ScienceField_txt.setEnabled(false);

        jLabel16.setText("Level :");

        jLabel12.setText("Class ID :");

        ClassID_txt.setEnabled(false);
        ClassID_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClassID_txtActionPerformed(evt);
            }
        });

        Capacity_txt.setEnabled(false);

        NumStudents_txt.setEnabled(false);

        LevelClass_txt.setEnabled(false);

        jLabel15.setText("Capacity :");

        jLabel14.setText("Number of Students :");

        jLabel13.setText("Science Field :");

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Options"));

        GradesButton.setText("Grades");
        GradesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GradesButtonActionPerformed(evt);
            }
        });

        StudentsButton.setText("Show All Students");
        StudentsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentsButtonActionPerformed(evt);
            }
        });

        EditGradesButton.setText("Edit Grades");
        EditGradesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditGradesButtonActionPerformed(evt);
            }
        });

        SubjectCompobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubjectCompoboxActionPerformed(evt);
            }
        });

        jLabel18.setText("Subject :");

        jLayeredPane1.setLayer(GradesButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(StudentsButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(EditGradesButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(SubjectCompobox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GradesButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EditGradesButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(StudentsButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SubjectCompobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(StudentsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubjectCompobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GradesButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EditGradesButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel13)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(LevelClass_txt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                    .addComponent(Capacity_txt, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(ScienceField_txt)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ClassID_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NumStudents_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 4, Short.MAX_VALUE))
                    .addComponent(jLayeredPane1))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(ClassID_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(NumStudents_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(ScienceField_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(Capacity_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(LevelClass_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredPane1)
                .addGap(21, 21, 21))
        );

        RefreshClassButton.setText("Refresh");
        RefreshClassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshClassButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TeacherClassesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RefreshClassButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(TeacherClassesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RefreshClassButton))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );

        jTabbedPane1.addTab("My Classes", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void New_TeacherPhone_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_New_TeacherPhone_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_New_TeacherPhone_txtActionPerformed

    private void New_TeacherAddress_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_New_TeacherAddress_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_New_TeacherAddress_txtActionPerformed

    private void New_TeacherEmail_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_New_TeacherEmail_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_New_TeacherEmail_txtActionPerformed

    private void TeacherPhone_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeacherPhone_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TeacherPhone_txtActionPerformed

    private void TeacherPosition_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeacherPosition_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TeacherPosition_txtActionPerformed

    private void TeacherID_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeacherID_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TeacherID_txtActionPerformed

    private void TeacherName_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeacherName_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TeacherName_txtActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        // TODO add your handling code here:
        New_TeacherEmail_txt.setText("");
        New_TeacherPhone_txt.setText("");
        New_TeacherAddress_txt.setText("");
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void DoneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoneButtonActionPerformed
        // TODO add your handling code here:
        String mail = New_TeacherEmail_txt.getText();
        String phone = New_TeacherPhone_txt.getText();
        String address = New_TeacherAddress_txt.getText();
        q.EditTeacherContactInfo(Tid, mail, phone, address);
    }//GEN-LAST:event_DoneButtonActionPerformed

    private void RefreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshButtonActionPerformed
        // TODO add your handling code here:
        res = q.ShowTeacherInfo(Tid);
        RefreshTextFields(res);
    }//GEN-LAST:event_RefreshButtonActionPerformed

    private void ClassID_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClassID_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClassID_txtActionPerformed

    private void RefreshClassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshClassButtonActionPerformed
        try {
            // TODO add your handling code here:
            String cid = (String) TeacherClassesComboBox.getSelectedItem();
            res = q.getClassInfo(cid);
            while(res.next())   {
                ClassID_txt.setText(res.getString("cid"));
                NumStudents_txt.setText(res.getString("csize"));
                ScienceField_txt.setText(res.getString("sciencefield"));
                Capacity_txt.setText(res.getString("capacity"));
                LevelClass_txt.setText(res.getString("level"));
                if("0".equals(LevelClass_txt.getText()))
                    LevelClass_txt.setText("Normal");
                else
                    LevelClass_txt.setText("High");
            }
        } catch (SQLException ex) {
            Logger.getLogger(TeacherFram.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_RefreshClassButtonActionPerformed

    private void StudentsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentsButtonActionPerformed
        try {
            // TODO add your handling code here:
            String cid = (String) TeacherClassesComboBox.getSelectedItem();
            DefaultTableModel mytable = (DefaultTableModel)ClassTable.getModel();
            res = q.getAllStudentInClass(cid);
            mytable.setColumnCount(0);
            mytable.setRowCount(0);
            mytable.setColumnCount(6);
            JTableHeader th = ClassTable.getTableHeader();
            TableColumnModel tcm = th.getColumnModel();
            tcm.getColumn(0).setHeaderValue("Student ID");
            tcm.getColumn(1).setHeaderValue("Fname");
            tcm.getColumn(2).setHeaderValue("Sname");
            tcm.getColumn(3).setHeaderValue("Lname");
            tcm.getColumn(4).setHeaderValue("G-Phone");
            tcm.getColumn(5).setHeaderValue("G-Email");
            th.repaint();
            while(res.next()){
               mytable.insertRow(mytable.getRowCount(), new Object[]{
               res.getString(1),
                res.getString(2),
                res.getString(3),
                res.getString(4),
                res.getString(5),
                res.getString(6)
            });          
            }
        } catch (SQLException ex) {
            Logger.getLogger(TeacherFram.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_StudentsButtonActionPerformed

    private void SubjectCompoboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubjectCompoboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubjectCompoboxActionPerformed

    private void GradesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GradesButtonActionPerformed
        try
        {
        // TODO add your handling code here:
            String cid = (String) TeacherClassesComboBox.getSelectedItem();
            String code = (String) SubjectCompobox.getSelectedItem();
            DefaultTableModel mytable = (DefaultTableModel)ClassTable.getModel();
            res = q.getGradesOfClassInSubject(code, cid);
            mytable.setColumnCount(0);
            mytable.setRowCount(0);
            mytable.setColumnCount(7);
            JTableHeader th = ClassTable.getTableHeader();
            TableColumnModel tcm = th.getColumnModel();
            tcm.getColumn(0).setHeaderValue("SID");
            tcm.getColumn(1).setHeaderValue("YWork(1)");
            tcm.getColumn(2).setHeaderValue("Mid (1)");
            tcm.getColumn(3).setHeaderValue("Final (1)");
            tcm.getColumn(4).setHeaderValue("YWork(2)");
            tcm.getColumn(5).setHeaderValue("Mid (2)");
            tcm.getColumn(6).setHeaderValue("Final (2)");
            th.repaint();
            while(res.next()){
               mytable.insertRow(mytable.getRowCount(), new Object[]{
               res.getString("sid"),
               res.getString("yw1"),
                res.getString("mt1"),
                res.getString("f1"),
                res.getString("yw2"),
                res.getString("mt2"),
                res.getString("f2")
            });          
            }
        } catch (SQLException ex) {
            Logger.getLogger(TeacherFram.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_GradesButtonActionPerformed

    private void EditGradesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditGradesButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel mytable = (DefaultTableModel)ClassTable.getModel();
        if(mytable.getColumnCount()== 0 || mytable.getColumnCount() == 6 ) {
            return;
        }
        mytable.setColumnCount(7);
        JTableHeader th = ClassTable.getTableHeader();
        TableColumnModel tcm = th.getColumnModel();
        tcm.getColumn(0).setHeaderValue("SID");
        tcm.getColumn(1).setHeaderValue("YWork(1)");
        tcm.getColumn(2).setHeaderValue("Mid (1)");
        tcm.getColumn(3).setHeaderValue("Final (1)");
        tcm.getColumn(4).setHeaderValue("YWork(2)");
        tcm.getColumn(5).setHeaderValue("Mid (2)");
        tcm.getColumn(6).setHeaderValue("Final (2)");
        th.repaint();
        ArrayList<String> arr = new ArrayList<>(6);
        arr.add(0,"yw1");
        arr.add(1,"mt1");
        arr.add(2,"f1");
        arr.add(3,"yw2");
        arr.add(4,"mt2");
        arr.add(5,"f2");
        if(mytable.getColumnCount()== 7 ) {
          for (int i = 0; i < mytable.getRowCount(); i++) {
                 for (int j = 1; j <= 6; j++) {
                        q.UpdateGrades((String) mytable.getValueAt(i, 0)
                                , arr.get(j-1), (String) mytable.getValueAt(i, j),
                                (String) SubjectCompobox.getSelectedItem());
                    }
              }
        }
    }//GEN-LAST:event_EditGradesButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
               
                /*if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }*/
                UIManager.setLookAndFeel("com.jtattoo.plaf.hifi.HiFiLookAndFeel");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherFram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JTextField Capacity_txt;
    private javax.swing.JTextField ClassID_txt;
    private javax.swing.JTable ClassTable;
    private javax.swing.JButton DoneButton;
    private javax.swing.JButton EditGradesButton;
    private javax.swing.JButton GradesButton;
    private javax.swing.JTextField LevelClass_txt;
    private javax.swing.JTextField New_TeacherAddress_txt;
    private javax.swing.JTextField New_TeacherEmail_txt;
    private javax.swing.JTextField New_TeacherPhone_txt;
    private javax.swing.JTextField NumStudents_txt;
    private javax.swing.JButton RefreshButton;
    private javax.swing.JButton RefreshClassButton;
    private javax.swing.JTextField ScienceField_txt;
    private javax.swing.JButton StudentsButton;
    private javax.swing.JComboBox<String> SubjectCompobox;
    private javax.swing.JTextField TeacherAddress_txt;
    private javax.swing.JTextField TeacherBus_Number_txt;
    private javax.swing.JComboBox<String> TeacherClassesComboBox;
    private javax.swing.JTextField TeacherEmail_txt;
    private javax.swing.JTextField TeacherID_txt;
    private javax.swing.JTextField TeacherName_txt;
    private javax.swing.JTextField TeacherPhone_txt;
    private javax.swing.JTextField TeacherPosition_txt;
    private javax.swing.JTable TeacherScheduleTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
